### ISSUE TITLE
Server side get `Connection reset by peer` when uploading files

### ISSUE THREAD

**Issue by CoderYellow** [fherbreteau/gatling-sftp#30]
seems you forget to close the outputstram here after uploading

https://github.com/fherbreteau/gatling-sftp/blob/e6249f4bd1065a2751fcbc2518fe90edf21f350e/src/main/scala/io/github/fherbreteau/gatling/sftp/client/SftpOperation.scala#L57

**Comment by fherbreteau** [comment]
Thanks for the info @CoderYellow.

Will be fixed in next release.

**Comment by fherbreteau** [comment]
New release of gatling-sftp has been published on maven central.
